ZEA-2086: Documentation for backup feature
zeabur/zeabur pull request #232
Opened 2023-10-31 10:26 UTC by hackerchai

2023-10-31 10:38 UTC, pan93412 requested changes

2023-10-31 10:38 UTC, pan93412 commented on docs/pages/deploy/backup.zh-CN.mdx
> +我们为所有部署在 Zeabur 上的 [Prebuilt Service](/prebuilt/intro) 提供了一个简单的方法来创建和恢复备份。
```suggestion
在生产环境和开发过程中，您可能需要为您的服务创建备份，增强应用的健壮性和可靠性。
我们为所有部署在 Zeabur 上的 [Prebuilt Service](/prebuilt/intro) 提供了一个简单的方法来创建和恢复备份。
```

2023-10-31 14:18 UTC, MichaelYuhe requested changes

2023-10-31 14:18 UTC, MichaelYuhe commented on docs/pages/deploy/backup.zh-CN.mdx
> +## 步骤一：挂起你的服务
挂起 -> 暂停合适一些

2023-11-01 04:05 UTC, MichaelYuhe approved these changes

2023-11-01 04:05 UTC, MichaelYuhe commented
cc @pan93412 for review

2023-11-01 04:18 UTC, pan93412 requested changes

2023-11-01 04:18 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +    上方提到的 [Prebuilt Service](/prebuilt/intro) , 是屬於服務下的一個子分類，[Prebuilt Service](/prebuilt/intro) 是有狀態服務，不同於 `Git Service` 是無狀態的， 所以 `Git Service` 不支援備份功能
```suggestion
    上方提到的 [Prebuilt Service](/prebuilt/intro) , 是屬於服務下的一個子分類，[Prebuilt Service](/prebuilt/intro) 是有狀態服務，不同於 `Git Service` 是無狀態的， 所以 `Git Service` 不支援備份功能。
```

2023-11-01 04:18 UTC, pan93412 commented on docs/pages/deploy/backup.zh-CN.mdx
> +    上方提到的 [Prebuilt Service](/prebuilt/intro) , 是属于服务下的一个子分类，[Prebuilt Service](/prebuilt/intro) 是有状态服务，不同于 `Git Service` 是无状态的， 所以 `Git Service` 不支持备份功能
```suggestion
    上方提到的 [Prebuilt Service](/prebuilt/intro) , 是属于服务下的一个子分类，[Prebuilt Service](/prebuilt/intro) 是有状态服务，不同于 `Git Service` 是无状态的， 所以 `Git Service` 不支持备份功能。
```

2023-11-01 04:18 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +此時你可以打開 **Settings** 頁籤，找到 `Danger Zone` 區域， 點擊 `Suspend Service` 按鈕暫停你的服務。
```suggestion
此時你可以打開 **Settings** 區塊，找到 `Danger Zone` 區域， 點選 `Suspend Service` 按鈕暫停你的服務。
```

2023-11-01 04:18 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +選擇你想要進行備份的服務，展開 **Backup** 頁籤，你會看到一個按鈕，用於為你的服務建立備份。
```suggestion
選擇你想要進行備份的服務，展開 **Backup** 區塊，你會看到一個按鈕，用於為你的服務建立備份。
```

2023-11-01 04:18 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +等待一段時間後，你可以看到備份已經建立完成，**Backup** 頁籤上會顯示 `SUCCESS` ，點擊此處即可下載備份文件。
```suggestion
等待一段時間後，你可以看到備份已經建立完成，**Backup** 區塊上會顯示 `SUCCESS` ，點選此處即可下載備份檔案。
```

2023-11-01 04:18 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +得到下載的文件後，你可以將其解壓縮並查看其中的內容。
```suggestion
得到下載的檔案後，你可以將其解壓縮並檢閱其中的內容。
```

2023-11-01 05:59 UTC, MichaelYuhe approved these changes

2023-11-01 06:19 UTC, pan93412 approved these changes

2023-11-01 06:19 UTC, merged