feat(docs/rabbitmq.toml) RabbitMq Docs/ Web
zeabur/zeabur pull request #237
Opened 2023-11-02 13:57 UTC by sudoskys

2023-11-02 14:03 UTC, pan93412 requested changes

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.en-US.mdx
> +```bash copy
```suggestion
```bash
```

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-CN.mdx
> +
```suggestion
```

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-CN.mdx
> +# Deploy RabbitMq 服务
```suggestion
# 部署 RabbitMQ 服务
```

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-CN.mdx
> +
```suggestion
```

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-CN.mdx
> +
```suggestion
```

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-CN.mdx
> +```bash copy
```suggestion
```bash
```

2023-11-02 14:03 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
推薦用 <https://zhconvert.org> 搭配「電腦詞彙」轉換。

2023-11-02 14:03 UTC, pan93412 commented on prebuilts/rabbitmq.toml
> +
```suggestion
```

2023-11-02 14:13 UTC, sudoskys reviewed
Request A review

2023-11-02 14:15 UTC, pan93412 requested changes

2023-11-02 14:15 UTC, pan93412 commented on docs/pages/databases/rabbitmq.en-US.mdx
> +After clicking on deploy, Zeabur will automatically deploy the Rabbitmq service for you.
```suggestion
After clicking on deploy, Zeabur will automatically deploy the RabbitMQ service for you.
```

2023-11-02 14:15 UTC, pan93412 commented on docs/pages/databases/rabbitmq.en-US.mdx
> +After deploying the Rabbitmq service, Zeabur will automatically inject the relevant environment variables into other services.
```suggestion
After deploying the RabbitMQ service, Zeabur will automatically inject the relevant environment variables into other services.
```

2023-11-02 14:15 UTC, pan93412 commented on docs/pages/databases/rabbitmq.en-US.mdx
> +The Rabbitmq service provides an online management interface, allowing you to manage the Rabbitmq service in the browser.
```suggestion
The RabbitMQ service provides an online management interface, allowing you to manage the RabbitMQ service in the browser.
```

2023-11-02 14:15 UTC, pan93412 commented on docs/pages/databases/rabbitmq.en-US.mdx
> +You can access the Rabbitmq service's online management interface by visiting `http://<RABBITMQ_HOST>:15672`.
```suggestion
You can access the RabbitMQ service's online management interface by visiting `http://<RABBITMQ_HOST>:15672`.
```

2023-11-02 14:15 UTC, pan93412 commented on docs/pages/databases/rabbitmq.en-US.mdx
> +You can use the DSN of the Rabbitmq service (that is, the connection string of the Rabbitmq service) through the variable `${RABBITMQ_URI}`.
```suggestion
You can use the DSN of the RabbitMQ service (that is, the connection string of the RabbitMQ service) with the variable `${RABBITMQ_URI}`.
```

2023-11-02 14:18 UTC, sudoskys reviewed
Rabbitmq->RabbitMQ

2023-11-02 14:20 UTC, pan93412 requested changes

2023-11-02 14:20 UTC, pan93412 commented
另外 zh-TW 的可以轉換了

2023-11-02 14:23 UTC, sudoskys reviewed
Resovle

2023-11-02 14:26 UTC, MichaelYuhe approved these changes

2023-11-02 14:29 UTC, pan93412 requested changes

2023-11-02 14:29 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
> +
```suggestion
```

2023-11-02 14:29 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
> +</Callout>
```suggestion
# 部署 RabbitMQ 服務

Zeabur 提供了 RabbitMQ 服務，讓你可以在 Zeabur 上一鍵部署 RabbitMQ 消息佇列。

<Callout type="info" emoji="ℹ️">
    目前 RabbitMQ 服務版本為 3-management。
</Callout>
```

2023-11-02 14:29 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
> +點擊部署後，Zeabur 會自動幫你部署 RabbitMQ 服務。
```suggestion
## 部署 RabbitMQ 服務

在你的專案中，點選 **建立服務** → **Prebuilt** ，在彈出列表搜尋列中搜尋 `RabbitMQ`。

![deploy](/deploy/common/select-service.en-US.png)

點選部署後，Zeabur 會自動幫你部署 RabbitMQ 服務。
```

2023-11-02 14:29 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
> +這裡的 <DATABASE_NAME> 是你自行新增的 Vhost 名稱。
```suggestion
## 環境變數

當你部署 RabbitMQ 服務後，Zeabur 會自動幫你注入相關環境變數到其他的服務中。

 - `RABBITMQ_HOST`
 - `RABBITMQ_PORT`
 - `RABBITMQ_DEFAULT_USER`
 - `RABBITMQ_DEFAULT_PASS`

有時候我們可以用自行新增的 `DATABASE_URL` 來取代上面的環境變數，例如：

```bash
amqp://<RABBITMQ_DEFAULT_USER>:<RABBITMQ_DEFAULT_PASS>@<RABBITMQ_HOST>:<RABBITMQ_PORT>/<DATABASE_NAME>
```

這裡的 `<DATABASE_NAME>` 是你自行新增的 Vhost 名稱。
```

2023-11-02 14:29 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
> +你通過訪問 `http://<RABBITMQ_HOST>:15672` 來訪問 RabbitMQ 服務的在線管理界面。
```suggestion
## 線上管理介面

RabbitMQ 服務提供了一個線上管理介面，讓你可以在瀏覽器中管理 RabbitMQ 服務。

可以進入 `http://<RABBITMQ_HOST>:15672` 來使用 RabbitMQ 服務的線上管理介面
```

2023-11-02 14:30 UTC, pan93412 commented on docs/pages/databases/rabbitmq.zh-TW.mdx
> +這裡的 <DATABASE_NAME> 是你自行新增的 Vhost 名稱。
看起來 suggestion block 壞了，建議手動修改。

2023-11-02 14:37 UTC, sudoskys reviewed
Apply zh-TW

2023-11-03 09:44 UTC, pan93412 approved these changes

2023-11-03 09:45 UTC, merged