add Milvus database
zeabur/zeabur pull request #244
Opened 2023-11-10 03:35 UTC by LemonHX

2023-11-10 05:56 UTC, yuaanlin commented
Please add some instructions to let users who deploy this prebuilt service can understand how to connect to it!

ref: https://github.com/zeabur/zeabur/blob/main/prebuilts/postgresql.toml#L33-L62

2023-11-10 07:01 UTC, pan93412 requested changes

2023-11-10 07:01 UTC, pan93412 commented on prebuilts/milvus.toml
> +MILVUS_PASSWORD = { default = "Milvus", expose = true, readonly = true }
Use `${PASSWORD}` for auto-generated password. https://github.com/zeabur/zeabur/blob/8c19e635df65119fb7360aade135137e62c18974/docs/pages/deploy/special-variables.zh-CN.mdx#L69

2023-11-10 07:39 UTC, LemonHX commented on prebuilts/milvus.toml
> +MILVUS_PASSWORD = { default = "Milvus", expose = true, readonly = true }
哦，这个我不知道它docker用的什么改，默认的是 Milvus

2023-11-10 07:41 UTC, LemonHX commented on prebuilts/milvus.toml
> +MILVUS_PASSWORD = { default = "Milvus", expose = true, readonly = true }
官方文档让你用python启动起来之后改

2023-12-12 03:27 UTC, pan93412 requested changes

2023-12-12 03:27 UTC, pan93412 commented on prebuilts/milvus.toml
> +type = "TCP"
現在支援多 ports 了，但你的 id 必須 unique。

2023-12-12 03:27 UTC, pan93412 commented on prebuilts/milvus.toml
> +
```suggestion
```

2023-12-12 03:27 UTC, pan93412 commented on prebuilts/milvus.toml
> +
```suggestion
```

2023-12-12 03:27 UTC, pan93412 commented on prebuilts/milvus.toml
> +showWhen = "PORT_FORWARDING"
```suggestion
```

showWhen 已經在 v4 捨棄了

2024-01-18 03:55 UTC, closed without merging