feat(prebuilt): add likit
zeabur/zeabur pull request #278
Opened 2023-12-10 11:50 UTC by CorrectRoadH

WIP

2023-12-10 11:56 UTC, pan93412 approved these changes

2023-12-10 12:46 UTC, pan93412 reviewed
中文翻譯的部分感覺反了，建議用 GPT 來做簡體跟繁體的翻譯。

2023-12-10 12:46 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-US.mdx
> +
```suggestion
```

2023-12-10 12:50 UTC, CorrectRoadH commented
> 中文翻譯的部分感覺反了，建議用 GPT 來做簡體跟繁體的翻譯。

好了

2023-12-10 12:57 UTC, pan93412 requested changes
CN 校对

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +
```suggestion
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +首先，我们需要建立一个项目。打开 [项目页面](https://dash.zeabur.com/projects)，你会看到一个专案列表。
```suggestion
首先，我们需要建立一个项目。打开 [项目页面](https://dash.zeabur.com/projects)，你会看到一个项目列表。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +请点选“创建服务”并选择“服务市场”，你将在列表中找到 Postgres
```suggestion
请点击“创建服务”并选择“Prebuilt”，你将在列表中找到 PostgreSQL。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +请点选“创建服务”并选择“服务市场”，你将在列表中找到 MySQL。
```suggestion
请点击“创建服务”并选择”Prebuilt”，你将在列表中找到 Redis。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +在专案页面，你会看到一个 "部署新服务" 按钮，点选它，然后选择 **Prebuilt**。你会在列表中找到 Likit
```suggestion
点击“创建服务”并选择“Prebuilt”，你将在列表中找到 Likit。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +打开服务页面的 "网络" 分页，然后点选 "生成域名" 或者 "定义域名"。
```suggestion
打开服务页面的 "网络" 分页，然后点选 "生成域名" 或者 "自定义域名"。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +关于如何绑定域名的更多资讯，请参考 [绑定网域](../deploy/domain-binding.zh-CN.mdx)。
```suggestion
关于如何绑定域名的更多信息，请参考 [绑定网域](../deploy/domain-binding.zh-CN.mdx)。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +在绑定好网域之后，你可以点选网域进入 Likit 的控制面板，开始使用 Likit。
```suggestion
在绑定好域名之后，你可以点选网域进入 Likit 的控制面板，开始使用 Likit。
```

2023-12-10 12:57 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +点选它或者按下确认键，我们将会开始为你部署 Likit
```suggestion
点击它或者按下确认键，我们将会开始为你部署 Likit。
```

2023-12-10 13:05 UTC, pan93412 commented
<img width="279" alt="image" src="https://github.com/zeabur/zeabur/assets/28441561/2fddcf69-11f1-4f99-8555-b26a7f10339e">

下次可以用這個按鈕，比較不會洗版～

2023-12-10 13:06 UTC, CorrectRoadH commented
> <img alt="image" width="279" src="https://private-user-images.githubusercontent.com/28441561/289360044-2fddcf69-11f1-4f99-8555-b26a7f10339e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTM4NTUsIm5iZiI6MTcwMjIxMzU1NSwicGF0aCI6Ii8yODQ0MTU2MS8yODkzNjAwNDQtMmZkZGNmNjktMTFmMS00Zjk5LTg1NTUtYjI2YTdmMTAzMzllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEzMDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2ZTlhMDM0OWU0ZDgyMGFiZjFiOWQ5YTU1ZDRjYjY5OWEwOWMxM2UyOTM1MDUyNDI2MzY0MjE3OTU2ZjVkOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._e8s-pXrPEdQ0QaNvpw6L1Ix7axgyFoyc6VFesqtH0M">
> 下次可以用這個按鈕，比較不會洗版～

好滴好滴。

2023-12-10 13:10 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-CN.mdx
> +在绑定好域名之后，你可以点选网域进入 Likit 的控制面板，开始使用 Likit。
```suggestion
在绑定好域名之后，你可以点选域名进入 Likit 的控制面板，开始使用 Likit。
```

2023-12-10 13:15 UTC, pan93412 requested changes

2023-12-10 13:15 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-US.mdx
```md
---
title: Deploy Likit
ogImageTitle: Deploy Likit
ogImageSubtitle: How to deploy Likit on Zeabur
---

import { Callout } from 'nextra-theme-docs'

# Deploying Likit

[Likit](https://github.com/CorrectRoadH/Likit) is a Backend as a Service for the like (vote, unlike, count) feature.

This article will show you how to deploy Likit on Zeabur in a minute.

## Method 1: Deploy from template (Recommended)

We've built a template for Likit. All you need is just one click on the button below, and then you will get a running Likit service.

[![Deploy on Zeabur](https://zeabur.com/button.svg)](https://zeabur.com/templates/KZOLHA?referralCode=CorrectRoadH)

## Method 2: Deploy from marketplace

### Step 1: Create a project

First, we need to create a project. Go to the [Projects page](https://dash.zeabur.com/projects), and you will see a list of your projects. Click the "Create Project" button at the end of the list.

### Step 2: Deploying Postgres

Before creating a Likit service, you should deploy a Postgres service.

Click "Add Service" and select "Marketplace". You will find PostgreSQL in the list.

![Deploying Postgres](/marketplace/likit/likit-postgres.png)

### Step 3: Deploying Redis

Before creating a Likit service, you should also deploy a Redis service.

Click "Add Service" and select "Marketplace". You will find Redis in the list.

![Deploying Redis](/marketplace/likit/likit-redis.png)

### Step 4: Deploy from prebuilt marketplace

After deploying Postgres and Redis, you can deploy Likit.

Go to the "Prebuilt" section in the marketplace. You will find Likit in the list.

### Step 5: Bind a domain

While you are waiting for the service to start and become operational, you can bind a domain to it. 
This domain can be your own or a free domain provided by Zeabur.

Open the "Domain" tab on the service page and click on "Generate Domain" or "Custom Domain".

For more information about how to bind a domain to your service, please refer to [Bind a domain](/deploy/domain-binding).

### Step 6: Start using Likit

After binding the domain, you can click on the domain to enter the Likit dashboard and get started.

![Likit Preview](/marketplace/likit/likit.png)
```

2023-12-10 13:15 UTC, pan93412 commented on docs/pages/marketplace/likit.zh-TW.mdx
> +關於如何綁定網域的更多資訊，請參考 [綁定網域](../deploy/domain-binding)。
```suggestion
關於如何綁定網域的更多資訊，請參考 [綁定網域](/deploy/domain-binding)。
```

2023-12-12 03:20 UTC, pan93412 approved these changes

2023-12-12 03:20 UTC, pan93412 commented
把 commit 清理一下吧，現在有點亂（

2023-12-12 03:21 UTC, pan93412 requested changes
把 commit 清理一下吧，現在有點亂（

```shell
git fetch origin main:main
git rebase -i main

# 上下移動 commit 然後 fixup
```

2023-12-12 03:24 UTC, CorrectRoadH commented
> 把 commit 清理一下吧，現在有點亂（
> 
> ```shell
> git fetch origin main:main
> git rebase -i main
> 
> # 上下移動 commit 然後 fixup
> ```

清理好了

2023-12-12 03:25 UTC, pan93412 approved these changes

2023-12-12 03:25 UTC, merged