ZEA-2367: Add dragonfly doc
zeabur/zeabur pull request #302
Opened 2024-01-10 08:01 UTC by hackerchai

2024-01-10 08:03 UTC, MichaelYuhe requested changes

2024-01-10 08:03 UTC, MichaelYuhe commented on docs/.vscode/CleanShot 2024-01-10 at 15.41.32@2x.png
duplicate image in wrong place

2024-01-10 08:06 UTC, MichaelYuhe approved these changes

2024-01-10 12:30 UTC, pan93412 submitted a review, later dismissed
1. No `copy` after `bash`.
2. Consider using Yuhang's Traditional Chinese dictionary or GPT 4 to convert zh-TW contents.

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.en-US.mdx
> +```bash copy
```suggestion
```bash
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.ja-JP.mdx
> +```bash copy
```suggestion
```bash
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-CN.mdx
> +```bash copy
```suggestion
```bash
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +[Dragonfly](https://www.dragonflydb.io/) 是一種簡單、高性能、低成本的內存數據存儲。Dragonfly 與 Redis API 完全兼容，但沒有 Redis 管理的複雜性。
```suggestion
[Dragonfly](https://www.dragonflydb.io/) 是一種簡單、高效能、低成本的記憶體內資料儲存空間。Dragonfly 與 Redis API 完全相容，但沒有 Redis 管理如此複雜。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +這篇文章將教你如何通過服務市場在 Zeabur 上部署自己的 Dragonfly 服務。
```suggestion
這篇文章將教你如何透過服務市場，在 Zeabur 上部署自己的 Dragonfly 服務。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +## 步驟一：建立項目
```suggestion
## 步驟一：建立專案
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +第一步，我們需要建立一個項目。進入 [項目](https://dash.zeabur.com/projects) 頁面，你會看到一個項目列表。
```suggestion
第一步，我們需要建立一個專案。進入 [專案](https://dash.zeabur.com/projects) 頁面，你會看到一個專案列表。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +點擊列表末尾的 "創建項目" 按鈕以創建一個新項目。
```suggestion
點選列表結尾的「建立專案」按鈕來建立一個新專案。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +按下 "cmd + k" 或者點擊 "Deploy New Service" 按鈕，然後選擇 "服務市場"。
```suggestion
按下 "cmd + k" 或者點選 "Deploy New Service" 按鈕，然後選擇「服務市場」。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +在列表中找到 Dragonfly 並點擊它以開始部署。
```suggestion
在列表中找到 Dragonfly 並點選它以開始部署。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +## 步驟三：獲取連接信息
```suggestion
## 步驟三：取得連線資訊
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +當你部署 Dragonfly 服務後，Zeabur 會自動幫你注入相關連接使用的環境變量到其他的服務中。
```suggestion
部署完 Dragonfly 服務後，Zeabur 會自動幫你注入和連線相關使用的環境變數到其他的服務中。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +有時候我們可以使用`DRAGONFLY_URI` 來取代上面的環境變量，例如：
```suggestion
可以選擇用 `DRAGONFLY_URI` 來取代上面的環境變數，例如：
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +```bash copy
```suggestion
```bash
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +我們也可以在控制台的 "Instructions" 板塊找到連接信息
```suggestion
我們也可以在控制台的「Instructions」區塊找到連線資訊。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +你可以在你的應用或者客戶端中使用上面的連接信息來連接 Dragonfly 服務。
```suggestion
你可以在你的應用程式或者用戶端中，使用上面的連線資訊來連線到 Dragonfly 服務。
```

2024-01-10 12:30 UTC, pan93412 commented on docs/pages/marketplace/dragonfly.zh-TW.mdx
> +因為 Dragonfly 與 Redis API 完全兼容，所以你可以使用任何支持 Redis 的客戶端來連接 Dragonfly 服務。
```suggestion
因為 Dragonfly 與 Redis API 完全相容，所以你可以使用任何支援 Redis 的用戶端來連接 Dragonfly 服務。
```

2024-01-11 09:43 UTC, MichaelYuhe approved these changes

2024-01-11 09:43 UTC, merged