ZEA-2385: Documentation for generate apikey
zeabur/zeabur pull request #303
Opened 2024-01-12 00:02 UTC by hackerchai

2024-01-12 00:49 UTC, pan93412 requested changes

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.en-US.mdx
> +# Issuing a REST API Request
```suggestion
# Send a REST API Request
```

issue (v.): to [produce](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/produce) or [provide](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/provide) something [official](https://dictionary.cambridge.org/zht/%E8%A9%9E%E5%85%B8/%E8%8B%B1%E8%AA%9E-%E6%BC%A2%E8%AA%9E-%E7%B9%81%E9%AB%94/official).

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.en-US.mdx
> +You can use any HTTP client library or within your application to issue requests. Here is an example:
```suggestion
You can use any HTTP client library or within your application to send requests. Here is an example:
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +title: 使用 API Key 和 Zeabur 集成
```suggestion
title: 使用 API Key 與 Zeabur 整合
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-CN.mdx
> +您可以通过任何语言发送 HTTP 请求 与我们的 GraphQL API / REST API 进行交互。在使用之前，您需要在 [Dashboard](https://dash.zeabur.com) 中创建一个 API Key。
```suggestion
您可以通过任何语言发送 HTTP 请求，与我们的 GraphQL API / REST API 进行交互。在使用之前，您需要在 [Dashboard](https://dash.zeabur.com) 中创建一个 API Key。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +ogImageSubtitle: 使用 API Key 和 Zeabur 集成
```suggestion
ogImageSubtitle: 使用 API Key 和 Zeabur 整合
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +您可以通過任何語言發送 HTTP 請求 與我們的 GraphQL API / REST API 進行交互。在使用之前，您需要在 [Dashboard](https://dash.zeabur.com) 中創建一個 API Key。
```suggestion
您可以使用任何語言傳送 HTTP 請求，來與我們的 GraphQL API / REST API 進行交互。在使用之前，您需要在 [Dashboard](https://dash.zeabur.com) 中建立一個 API Key。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +# 創建 API Key
```suggestion
# 建立 API Key
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +在 [Dashboard](https://dash.zeabur.com/) 中，點擊右側下拉菜單的 `Settings`，然後點擊 左側邊欄 `Developer` , 即可看到開發者選項。
```suggestion
在 [Dashboard](https://dash.zeabur.com/) 中，點選右側下拉選單的 `Settings`，然後點選左側邊欄的 `Developer` , 即可看到開發者選項。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +找到 `API Key` 區域，點擊 `Generate New Token` 按鈕即可生成一個 API Key。
```suggestion
找到 `API Key` 區域，點選 `Generate New Token` 按鈕即可產生一個 API Key。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +點擊 `View` 按鈕即可查看 API Key。
```suggestion
點選 `View` 按鈕即可檢視 API Key。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +點擊 `Copy` 按鈕即可複製 API Key。
```suggestion
點選 `Copy` 按鈕即可複製 API Key。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +Zeabur API 可以選擇使用 API Key 進行身份驗證。保證您已經生成了有效的 API Key。
```suggestion
Zeabur API 可以選擇使用 API Key 進行身分驗證。請先確保您已經產生了有效的 API Key。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +所有 API 請求都應在 `Authorization` HTTP 頭部中包含您的 API Key ，如下所示：
```suggestion
所有 API 請求都應在 `Authorization` HTTP header 中包含您的 API Key ，如下所示：
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +# 發出 REST API 請求
```suggestion
# 送出 REST API 請求
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +您可以使用任何 HTTP 客戶端庫或者在您的應用中來發出請求。下面是示例：
```suggestion
您可以使用任何 HTTP 用戶端函式庫或者在您的應用程式中送出請求。下面是範例：
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +您可以將以下命令黏貼到終端中以運行您的第一個 REST API 請求。確保將 `$ZEABUR_API_KEY` 替換為您的 API Key
```suggestion
您可以將以下命令貼到終端機中，來執行您的第一個 REST API 請求。確定您已經將 `$ZEABUR_API_KEY` 替換為您的 API Key：
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +此處查詢當前用戶的信息。您應該收到類似於以下內容的響應：
```suggestion
這將查詢目前使用者的資訊。您應收到如下面內容的回應。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +現在您已經成功地使用 API Key 進行了身份驗證，您可以使用 API Key 來訪問其他 REST API 了。
```suggestion
現在您已成功使用 API Key 進行了身分驗證，您可以使用 API Key 來存取其他 REST API 了。
```

2024-01-12 00:49 UTC, pan93412 commented on docs/pages/developer/use-api-key.zh-TW.mdx
> +GrapQL API 的訪問方式與上述相同，只是請求方式不同。您可以在 [GraphQL Playground](https://gateway.zeabur.com/graphql) 中嘗試 GraphQL API。
```suggestion
GrapQL API 的存取方式與上述相同，只是請求方式不同。您可以在 [GraphQL Playground](https://gateway.zeabur.com/graphql) 中嘗試 GraphQL API。
```

2024-01-12 07:11 UTC, pan93412 approved these changes

2024-01-14 11:50 UTC, yuaanlin approved these changes

2024-01-14 11:50 UTC, merged