ZEA-2452: Add guide of how to use config
zeabur/zeabur pull request #313
Opened 2024-01-19 08:19 UTC by hackerchai

2024-01-19 09:52 UTC, MichaelYuhe approved these changes

2024-01-19 16:34 UTC, pan93412 requested changes
Tweak the sentence with GPT's Improve Writing feature.

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/_meta.en-US.json
> +  "config-edit": "Config Edit"
```suggestion
  "config-edit": "Config Editing"
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +When running a service, you can use a configuration file to customize some parameters of the service. Zeabur provides a configuration file editor that can specify the storage location and content of
```suggestion
When running a service, you can customize it by using a configuration file. Zeabur provides a configuration file editor that allows you to specify the path and content of your configuration. The configuration file is automatically mounted upon service startup.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +Here, we use [nginx](https://nginx.com/) as a front proxy for [vaultwarden](https://github.com/dani-garcia/vaultwarden) to demonstrate the process of editing ngnix custom configuration files via the
```suggestion
We use [NGINX](https://nginx.com/) as a front proxy for [vaultwarden](https://github.com/dani-garcia/vaultwarden) to show how to edit NGINX custom configuration files using the configuration file editor.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +Create Prebuilt Services in the aforementioned Project , with service names namely nginx and vaultwarden.
```suggestion
Create your NGINX and Vaultwarden prebuilt services in the project you created in Step One.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +![Create Ngnix Service](/deploy/config-edit/create-nginx-service.en-US.png)
```suggestion
![Create NGINX Service](/deploy/config-edit/create-nginx-service.en-US.png)
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +1. In the Services column, click `Settings` tab for the nginx service, click the drop-down button to find the `Configs` section, and click the `Open Config Editor` button to enter the configuration f
```suggestion
Click on the `Settings` tab in the Services section for your NGINX service. Then, locate the `Configs` section in the expanded tab. Next, click the `Open Config Editor` button to access the configuration file editor.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +2. In the opened window, click the `Add Config file` button, to add a configuration file. In the popped-up window, input the path and name of the configuration file in the `Config Path` input box. He
```suggestion
2. In the editor, we click on the `Add Config file` button to add a configuration file. In the sheet that appears, enter the filename and path for your configuration in the `Config Path` text box. In this example, we will use `/etc/nginx/nginx.conf`. Finally, click the `Save Config` button.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +    The `Config Path` above requires the absolute path of the configuration file, please configure in line with the actual situation.
```suggestion
    The `Config Path` above must be an absolute path. Customize it according to your requirements.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +3. Depending on the requirements, edit the content of the configuration file. Here, we add a `server` configuration for reverse-proxying the vaultwarden service.
```suggestion
3. Edit the configuration file according to your requirements. In this case, we will add a `server` configuration to enable reverse-proxying for our vaultwarden service.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +In the file content above, `vaultwarden.zeabur.internal` in the `proxy_pass` block is the service name of Vaultwarden. Here, we used [Private Network](/deploy/private-networking) feature, which allow
```suggestion
To allow others to access our internal Vaultwarden through our NGINX service, we use the `proxy_pass vaultwarden.zeabur.internal` directive in NGINX. This instructs NGINX to proxy all requests from `/` to Vaultwarden. We make use of the [Private Network](/deploy/private-networking) feature to access Vaultwarden with a fixed hostname within our private network.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +In the file above, we added a custom log format and log storage location, in addition to several custom nginx optimization parameters.
```suggestion
```

I think this is unnecessary because it's derived from the default NGINX configuration of Zeabur.

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +4. Click the `Save` button to save the configuration file.
```suggestion
4. Click the `Save` button to save your configuration file.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +In the above steps, we already concluded the editing of the configuration file. Next, we need to restart the service, find the `Instructions` column, find the `Restart` button, and click to restart t
```suggestion
We have completed the configuration of NGINX in the previous steps. Now, we need to restart the service. Go to the `Instructions` section and click the `Restart` button to apply your configuration changes.
```

2024-01-19 16:34 UTC, pan93412 commented on docs/pages/deploy/config-edit.en-US.mdx
> +After [binding the domain name](/deploy/domain-binding) under the nginx service, you can access the vaultwarden service through the domain name.
```suggestion
Once you have [bound a domain name](/deploy/domain-binding) to your NGINX service, you can access the vaultwarden service using your domain name.
```

2024-01-19 16:47 UTC, pan93412 requested changes
Porting some en-US changes to zh-TW. You may need to port some zh-TW changes back to zh-CN.

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/_meta.zh-TW.json
> +  "config-edit": "配置檔案編輯"
```suggestion
  "config-edit": "編輯設定檔"
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +title: 配置檔案編輯
```suggestion
title: 編輯設定檔
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +ogImageTitle: 配置檔案編輯
```suggestion
ogImageTitle: 編輯設定檔
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +ogImageSubtitle: 配置檔案編輯
```suggestion
ogImageSubtitle: 編輯設定檔
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +# 配置檔案編輯
```suggestion
# 編輯設定檔
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +在執行服務時，可以透過配置檔案來自訂服務的一些參數，Zeabur 提供了一個配置檔案編輯器，可以透過編輯器來指定配置檔案的儲存位置和內容。在服務啟動時，會自動掛載配置檔案。
```suggestion
在執行服務時，你可以透過設定檔來自訂服務的各項設定，Zeabur 提供了設定檔編輯器，讓你可以透過編輯器來指定設定檔的儲存位置和內容。在服務啟動時，會自動掛載配置檔案。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +這裡我們使用 [nginx](https://nginx.com/) 作為前置代理 [vaultwarden](https://github.com/dani-garcia/vaultwarden)，來示範配置檔案編輯器編輯 ngnix 自訂配置檔案的過程。
```suggestion
這裡我們使用 [NGINX](https://nginx.com/) 反向代理內網的 [vaultwarden](https://github.com/dani-garcia/vaultwarden) 服務，來示範設定檔編輯器更改 NGINX 設定檔的流程。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +在上述 Project 中分別建立 Prebuilt Service ，服務名稱分別為 nginx 和 vaultwarden。
```suggestion
在上述 Project 中分別建立 NGINX 和 Vaultwarden 的 Prebuilt Service。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +![建立 Ngnix 服務](/deploy/config-edit/create-nginx-service.en-US.png)
```suggestion
![建立 NGINX 服務](/deploy/config-edit/create-nginx-service.en-US.png)
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +## 步驟三：編輯 Nginx 服務配置檔案
```suggestion
## 步驟三：編輯 Nginx 服務設定檔
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +1. 在 Services 一欄中，點擊 nginx 服務的 `Settings` 欄目，點擊下拉按鈕找到 `Configs` 部分，點擊 `Open Config Editor` 按鈕，進入配置檔案編輯器。
```suggestion
1. 在 Services 區中，點選 NGINX 服務的 `Settings` 區塊的下拉按鈕，找到 `Configs` 部分後點選 `Open Config Editor` 按鈕，進入設定檔編輯器。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +![打開配置檔案編輯器](/deploy/config-edit/open-config-editor.en-US.png)
```suggestion
![打開設定檔編輯器](/deploy/config-edit/open-config-editor.en-US.png)
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +2. 在打開的視窗中，點擊 `Add Config file` 按鈕，添加一個配置檔案。在彈出的視窗中，在 `Config Path` 輸入框輸入配置檔案的路徑和名稱，這裡我們輸入 `/etc/nginx/nginx.conf`，點擊 `Save Config` 按鈕。
```suggestion
2. 在打開的編輯器中，點選 `Add Config file` 按鈕新增一個設定檔。在彈出表單的 `Config Path` 輸入框打上設定檔的路徑和名稱，這裡我們輸入 `/etc/nginx/nginx.conf`，接著點選 `Save Config` 按鈕。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +![添加配置檔案](/deploy/config-edit/create-new-config.en-US.png)
```suggestion
![新增設定檔](/deploy/config-edit/create-new-config.en-US.png)
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +    上方的 `Config Path` 需要輸入配置檔案的絕對路徑，請根據實際情況配置。
```suggestion
    上方的 `Config Path` 需要輸入設定檔的絕對路徑，請根據實際情況調整。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +3. 根據需求，編輯配置檔案的內容，這裡我們添加了一個 `server` 配置，用於反向代理 vaultwarden 服務。
```suggestion
3. 根據需求編輯設定檔的內容，這裡我們新增一個 `server` 區塊，用來反向代理 Vaultwarden 服務。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +在上面的文件裡我們添加了自訂的日誌格式和日誌儲存位置，並且自訂了若干 nginx 最佳化參數
```suggestion
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +上面的文件內容中，`proxy_pass` 程式碼塊中的 `vaultwarden.zeabur.internal` 是 vaultwarden 服務的服務名，這裡我們使用了 [Private Network](/deploy/private-networking) 功能，可以透過固定的主機名稱來使用內網訪問服務。
```suggestion
為了讓其他人可以透過 NGINX 服務存取我們的內部 Vaultwarden，我們在 NGINX 中使用 `proxy_pass http://vaultwarden.zeabur.internal:80;` 指令，表示讓 NGINX 將連線到此處的所有請求都代理到 Vaultwarden。我們利用 [服務內網](/deploy/private-networking) 功能，在我們的私有網路中透過固定主機名稱存取 Vaultwarden。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +4. 點擊 `Save` 按鈕，儲存配置檔案。
```suggestion
4. 點選 `Save` 按鈕儲存設定。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +在上述步驟中，我們已經完成了配置檔案的編輯，接下來我們需要重啟服務，找到 `Instructions` 欄目，找到 `Restart` 按鈕，點擊重啟服務，以使配置檔案生效。
```suggestion
在上述步驟中，我們已經完成了設定檔的編輯，接下來我們需要重新啟動服務。找到 `Instructions` 區塊，點選其中的 `Restart` 按鈕重新啟動服務，以使設定檔生效。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +在 nginx 服務下進行 [綁定域名](/deploy/domain-binding) 後，就可以透過域名訪問 vaultwarden 服務。
```suggestion
[將網域綁定到 NGINX 服務後](/deploy/domain-binding)，即可透過網域造訪 vaultwarden 服務。
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +![訪問 Vaultwarden](/deploy/config-edit/vultwarden-service.en-US.png)
```suggestion
![造訪 Vaultwarden](/deploy/config-edit/vultwarden-service.en-US.png)
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +![重啟服務](/deploy/config-edit/restart-service.en-US.png)
```suggestion
![重新啟動服務](/deploy/config-edit/restart-service.en-US.png)
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +![儲存配置檔案](/deploy/config-edit/save-config.en-US.png)
```suggestion
![儲存設定檔](/deploy/config-edit/save-config.en-US.png)
```

2024-01-19 16:47 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-TW.mdx
> +## 步驟四：重啟服務
```suggestion
## 步驟四：重新啟動服務
```

2024-01-22 02:55 UTC, MichaelYuhe approved these changes

2024-01-22 03:11 UTC, pan93412 requested changes
The Japanese translation should be updated too.

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +ogImageSubtitle: 配置文件编辑
```suggestion
title: 编辑配置文件
ogImageTitle: 编辑配置文件
ogImageSubtitle: 编辑配置文件
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +# 配置文件编辑
```suggestion
# 编辑配置文件
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +在运行服务时，可以通过配置文件来自定义服务的一些参数，Zeabur 提供了一个配置文件编辑器，可以通过编辑器来指定配置文件的存储位置和内容。在服务启动时，会自动挂载配置文件。
```suggestion
在执行服务时，你可以通过配置文件来自定义服务的各项设置，Zeabur 提供了配置文件编辑器，让你可以通过编辑器来指定配置文件的存储位置和内容。在服务启动时，会自动挂载配置文件。
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +这里我们使用 [nginx](https://nginx.com/) 作为前置代理 [vaultwarden](https://github.com/dani-garcia/vaultwarden)，来演示配置文件编辑器编辑 ngnix 自定义配置文件的过程。
```suggestion
这里我们使用 [NGINX](https://nginx.com/) 反向代理内网的 [vaultwarden](https://github.com/dani-garcia/vaultwarden) 服务，来示范配置文件编辑器更改 NGINX 配置文件的流程。
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +在上述 Project 中分别创建 Prebuilt Service ，服务名称分别为 nginx 和 vaultwarden。
```suggestion
在上述项目中分别建立 NGINX 和 Vaultwarden 的 Prebuilt Service。
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +![创建 Ngnix 服务](/deploy/config-edit/create-nginx-service.en-US.png)
```suggestion
![创建 NGINX 服务](/deploy/config-edit/create-nginx-service.en-US.png)
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +上面的文件内容中，`proxy_pass` 代码块中的 `vaultwarden.zeabur.internal` 是 vaultwarden 服务的服务名，这里我们使用了 [Private Network](/deploy/private-networking) 功能，可以通过固定的主机名称来使用内网访问服务。
```suggestion
为了让其他人可以通过 NGINX 服务访问我们的内部 Vaultwarden，我们在 NGINX 中使用 `proxy_pass http://vaultwarden.zeabur.internal:80;` 指令，表示让 NGINX 将连接到此处的所有请求都代理到 Vaultwarden。这里我们使用了 [Private Network](/deploy/private-networking) 功能，在我们的私有网络中通过固定主机名称访问 Vaultwarden。
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +
```suggestion
```

2024-01-22 03:11 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +在 nginx 服务下进行 [绑定域名](/deploy/domain-binding) 后，就可以通过域名访问 vaultwarden 服务。
```suggestion
[将域名绑定到 NGINX 服务后](/deploy/domain-binding)，就可以通过域名访问 vaultwarden 服务。
```

2024-01-22 03:53 UTC, pan93412 commented on docs/pages/deploy/_meta.zh-CN.json
> +  "config-edit": "配置文件编辑"
```suggestion
  "config-edit": "编辑配置文件"
```

2024-01-22 03:53 UTC, pan93412 commented on docs/pages/deploy/config-edit.zh-CN.mdx
> +
```suggestion
```

2024-01-22 03:57 UTC, pan93412 approved these changes

2024-01-22 03:58 UTC, pan93412 commented
For mergers: Squash the commit before merging.

2024-01-22 04:02 UTC, merged