translate: complete the translated content
zeabur/zeabur pull request #400
Opened 2024-04-14 15:01 UTC by ikxin

2024-04-14 15:45 UTC, pan93412 requested changes
Awesome works! I have only some suggestion for this.

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/billing.json
> +        "current": "當前方案",
```suggestion
        "current": "目前方案",
```

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/billing.json
> +        "no-method": "你還沒有綁定付款方式。你將需要手動來打卡延長試用期限，以保證服務穩定運行。",
```suggestion
        "no-method": "你還沒有綁定付款方式。你將需要手動打卡延長試用期限，以保證服務穩定運作。",
```

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/billing.json
> +        "alipay": "你綁定了支付方式為",
```suggestion
        "alipay": "你綁定了付款方式為",
```

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/project.json
> +        "title": "專案設置",
```suggestion
        "title": "專案設定",
```

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/project.json
> +            "title": "通用設置",
```suggestion
            "title": "一般設定",
```

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/service.json
> +        "no-domain": "為您的服務創建一個域名"
```suggestion
        "no-domain": "為您的服務建立一個域名"
```

2024-04-14 15:45 UTC, pan93412 commented on dashboard/locales/zh-TW/service.json
> +        "title": "網絡連接"
```suggestion
        "title": "網路連線"
```

2024-04-15 02:42 UTC, MichaelYuhe commented
Great work, thanks for the help!

2024-04-15 02:42 UTC, MichaelYuhe approved these changes

2024-04-15 13:24 UTC, pan93412 approved these changes

2024-04-16 02:14 UTC, merged