prebuilt: add directus
zeabur/zeabur pull request #429
Opened 2024-05-10 07:21 UTC by MichaelYuhe

2024-05-10 08:17 UTC, MichaelYuhe commented
#416

2024-05-11 06:01 UTC, pan93412 requested changes

2024-05-11 06:01 UTC, pan93412 commented on prebuilts/directus.toml
> +dir = "/uploads:/directus/uploads"
```suggestion
dir = "/directus/uploads"
```

2024-05-11 06:01 UTC, pan93412 commented on prebuilts/directus.toml
> +dir = "/extensions:/directus/extensions"
```suggestion
dir = "/directus/extensions"
```

2024-05-12 04:28 UTC, pan93412 approved these changes

2024-05-12 07:34 UTC, merged