docs: backup without suspend
zeabur/zeabur pull request #453
Opened 2024-05-26 06:21 UTC by MichaelYuhe

2024-05-26 15:40 UTC, pan93412 requested changes

2024-05-26 15:40 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +    上文提到的[預建置服務](/prebuilt/intro)屬於服務類別的子類別。[預建置服務](/prebuilt/intro)是有狀態的服務，不同於無狀態的`Git Service`。
Prebuilt 不要翻譯

2024-05-26 15:40 UTC, pan93412 commented on docs/pages/deploy/backup.zh-TW.mdx
> +打開 [Zeabur控制面板](https://dash.zeabur.com)，導航到您想要備份的服務頁面，打開**備份**頁籤，您將看到一個按鈕，用於為您的服務建立備份。
```suggestion
打開 [Zeabur Dashboard](https://dash.zeabur.com)，導航到您想要備份的服務頁面，打開**備份**頁籤，您將看到一個按鈕，用於為您的服務建立備份。
```

2024-05-27 02:26 UTC, yuaanlin approved these changes

2024-05-27 07:11 UTC, merged