docs: subscription doc for en-US
zeabur/zeabur pull request #91
Opened 2023-04-29 14:50 UTC by MichaelYuhe

2023-04-29 14:59 UTC, pan93412 requested changes

2023-04-29 14:59 UTC, pan93412 commented on pages/billing/subscription.en-US.mdx
> +There're 3 types of plans on Zeabur: **Free Plan**, **Developer Plan** and **Team Plan**.
Usually we prefer to express “there are” as “there are” instead of the simplified version.

2023-04-29 14:59 UTC, pan93412 commented on pages/billing/subscription.en-US.mdx
> +You can subscribe to a plan with your credit card, paying with USD.
`paying in USD`. [ref](https://www.bill.com/blog/pay-us-dollars-or-foreign-currency)

2023-04-29 14:59 UTC, pan93412 commented on pages/billing/subscription.en-US.mdx
> +If you don't have a credit card that supports Stripe service, you can subscribe to a plan with your Alipay account, paying with CNY.
How about: *If you don't have a credit card that is compatible with Stripe service*

2023-04-29 14:59 UTC, pan93412 commented on pages/billing/subscription.en-US.mdx
> +If you don't have a credit card that supports Stripe service, you can subscribe to a plan with your Alipay account, paying with CNY.
paying in CNY.

2023-04-29 14:59 UTC, pan93412 commented on pages/billing/subscription.en-US.mdx
> +> **Note**: Once you've subscribed to a plan with Alipay, you can't change back to credit card subscription.
> you can't change back to credit card subscription.

How about rewrite it to:

> you can't subscribe with your credit card anymore.

2023-04-29 14:59 UTC, pan93412 commented on pages/billing/subscription.en-US.mdx
> +## Contact US
How about changing `US` to the lowercase one to not be confused with United States? 😂

2023-04-29 15:05 UTC, itsalicelee commented on pages/billing/subscription.en-US.mdx
> +You can deploy your application with **Free Plan**, but there will be some limitations.
deploy your applications

2023-04-29 15:05 UTC, itsalicelee commented on pages/billing/subscription.en-US.mdx
> +To use Zeabur, you need to subscribe to one of the plans, the default plan is **Free Plan**.
L14-15 有一點點容易誤會，感覺在說一定要subscribe才能使用，但其實default free plan就可以使用了，所以其實不一定要subscribe(?) 可以想想要怎麼說明這件事比較好

2023-04-29 15:11 UTC, MichaelYuhe commented on pages/billing/subscription.en-US.mdx
> +To use Zeabur, you need to subscribe to one of the plans, the default plan is **Free Plan**.
确实，我再重新组织一下语言

2023-04-30 11:56 UTC, pan93412 requested changes

2023-04-30 11:56 UTC, pan93412 commented on pages/billing/subscription.zh-TW.mdx
```md
---
title: 訂閱
ogImageTitle: 訂閱
ogImageSubtitle: 訂閱 Zeabur
---

# 訂閱

## 什麼是訂閱？

Zeabur 有 3 種類型的方案：**免費方案**、**開發者方案** 和 **團隊方案**。
你可以在 [方案](/billing/plans) 頁面檢視每個方案的詳細資訊。

如果你沒有訂閱任何方案，你將預設和 **免費方案** 使用者一樣，擁有同樣的權利與限制。

## 如何訂閱？

Zeabur 的訂閱以 [Stripe](https://stripe.com/) 為基礎。

有兩種方式可以訂閱方案：**信用卡** 和 **支付寶**。

### 用信用卡訂閱

你可以用信用卡訂閱方案，以美元付款。

- 在訂閱前設定卡片：在 [帳單頁面](https://dash.zeabur.com/account/billing)，你可以在 **付款方式** 部分設定你的信用卡。在你輸入完信用卡資訊後，點選 **新增** 按鈕儲存你的信用卡，然後你就可以在 [方案頁面](https://dash.zeabur.com/update-plan) 點選 **訂閱** 按鈕來更新你的訂閱。
- 在訂閱時設定卡片：在 [升級方案頁面](https://dash.zeabur.com/update-plan) 選擇一個方案，然後輸入你的信用卡資訊，點選 **訂閱** 按鈕，即會重新導向至 Stripe 的付款頁面。填寫表單後，即完成方案的訂閱，同時也會存入你的信用卡資訊。

### 用支付寶訂閱

如果你沒有支援 Stripe 的信用卡，你可以用支付寶訂閱方案，以人民幣付款。

前往 [方案頁面](https://dash.zeabur.com/update-plan)，選擇一個方案，點選 **No Credit Card?** 連結，你將被重新導向至 Stripe 的付款頁面。這裡你可以用支付寶訂閱方案。

> **注意**：一旦你用支付寶訂閱了方案，你便無法再選擇用信用卡訂閱。

## 如何降級到免費方案

如果你訂閱了付費方案，你也可以隨時降級到 **免費方案**。

前往 [方案頁面](https://dash.zeabur.com/update-plan)，選擇 **免費方案**，點選 **訂閱** 按鈕，你將被重新導向到 Stripe 的付款頁面。這裡你可以選擇取消你的訂閱。

## 聯絡我們

如果你有關於訂閱的任何問題，請到我們的 [Discord 群組](https://discord.gg/DrdGCvXEyY) 聯絡我們。
```

2023-04-30 11:56 UTC, pan93412 commented on pages/billing/subscription.zh-CN.mdx
> +- 在订阅时设置卡片：在 [升级方案页面](https://dash.zeabur.com/update-plan) 选择一个方案，然后输入你的信用卡信息，点击 **订阅** 按钮，你将被重定向到 Stripe 的支付页面，填写表单后，你将订阅该方案，并且你的信用卡信息将被保存。
> 填写表单后，你将订阅该方案，并且你的信用卡信息将被保存。

How about:

> 填写表单后，即完成方案的订阅，同时也会存入你的信用卡信息。

2023-04-30 11:56 UTC, pan93412 commented on pages/billing/subscription.zh-CN.mdx
> +前往 [方案页面](https://dash.zeabur.com/update-plan)，选择 **免费方案**，点击 **订阅** 按钮，你将被重定向到 Stripe 的支付页面，在这里你选择取消你的订阅。
> 在这里你选择取消你的订阅

How about

> 这里你可以选择取消你的订阅

2023-04-30 11:56 UTC, pan93412 commented on pages/billing/subscription.zh-CN.mdx
> +> **Note**: Once you've subscribed to a plan with Alipay, you can't subscribe with your credit card anymore.
这段英文应当可以删除。

2023-04-30 11:56 UTC, pan93412 commented on pages/billing/subscription.zh-CN.mdx
> +前往 [方案页面](https://dash.zeabur.com/update-plan)，选择一个方案，点击 **No Credit Card?** 链接，你将被重定向到 Stripe 的支付页面，在这里你可以用支付宝订阅方案。
「在这里」可以简化成「这里」

> 这里你可以用支付宝订阅方案。

2023-05-01 07:07 UTC, merged